# Site settings
name: 修德的博客
email: 1287343381@qq.com
author: X/D
url: https://xiude.github.io
resume_site: https://xiude.github.io/me/
github: https://github.com/xiude/
baseurl: ""  #根目录
# description: 假如生活欺骗了你，不要悲伤，不要哭泣。
description: 纵有疾风起，奋斗不可弃。
motto: 时间一分一秒逝去，知识一点一滴积累。
#motto: 如果生活欺骗了你，不要悲伤，不要哭泣。
banner: 我想带你去看绚丽的山峦，去看秀丽的溪谷，这份心情，人类是如何称呼的呢。
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: maoxiaoke
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xiude
